### PR TITLE
Bugfix 115 bug in automatic name prefix when adding new icon

### LINKED ISSUE #115: Bug in automatic name prefix when adding new icon
When adding new icon, app demands user to include "icon_" in the given icon name, but it also adds another "icon_" prefix automatically after user has saved icon.

### PR DESCRIPTION
**Pull request by lauriLukkarinen**
Resolves #115

### CODE REVIEW

File: src/components/pages/ApplicationEditor.tsx [hunk 1]
```diff
@@ -108,26 +106,27 @@ class ApplicationEditor extends React.Component<Props, State> {
...
+    } = this.props;
 
     if (!auth || !auth.token) {
       return;
     }
 
-    document.addEventListener('mousemove', e => this.handleMousemove(e));
-    document.addEventListener('mouseup', e => this.handleMouseup(e));
+    document.addEventListener('mousemove', this.handleMousemove);
+    document.addEventListener('mouseup', this.handleMouseup);
```
Comment (jarinykanen) [inline src/components/pages/ApplicationEditor.tsx:129]:
```suggestion
    document.addEventListener("mousemove", this.handleMousemove);
    document.addEventListener("mouseup", this.handleMouseup);
```

**Review by jarinykanen — APPROVED** [review]
