### PR TITLE
Fixed issue #259

### LINKED ISSUE #259: Parent locks on non page resources

### PR DESCRIPTION
**Pull request by anttileppa**
Resolves #259

### CODE REVIEW

File: src/components/pages/ApplicationEditor.tsx [hunk 1]
```diff
@@ -1090,8 +1090,9 @@ class ApplicationEditor extends React.Component<Props, State> {
       return true;
     }
 
-    const parentId = resource?.parentId;
-    if (parentId && this.shouldLockParent(resource.type)) {
+    const parentResource = this.findResourceById(resource?.parentId);
+    if (parentResource && this.shouldLockParent(parentResource.type)) {
+      const parentId = parentResource.id!!;
```
Comment (EVP1989) [inline src/components/pages/ApplicationEditor.tsx:1095]:
```suggestion
      const parentId = parentResource.id!;
```

**Review by EVP1989 — APPROVED** [review]
Approved with suggestion
